Shop/ViewModels/CarsListViewModel.cs
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class CarsListViewModel
    {
        public IEnumerable<Car> allCars { get; set; }

        public string currCategory { get; set; }
    }
}

Shop/ViewModels/HomeViewModel.cs
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Car> favCars { get; set; }
    }
}

Shop/ViewModels/ShopCartViewModel.cs
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class ShopCartViewModel
    {
        public ShopCart shopCart { get; set; }
    }
}

Shop/Controllers/CarsController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class CarsController : Controller
    {
        //контроллер содержит различные функции, при вызове которых у нас будет возвращаться
        //тип данных как ViewResult - тип данных в виде HTML страницы
        private IAllCars _allCars;
        private readonly ICarsCategory _allCategories;

        //создадим конструктор
        public CarsController(IAllCars iAllCars, ICarsCategory iCarsCat)
        {
            _allCars = iAllCars;
            _allCategories = iCarsCat;
        }

        [Route("Cars/List")]
        [Route("Cars/List/{category}")]
        //функция которая возвращает View. Список всех товаров
        public ViewResult List(string category)
        {
            string _category = category;
            //в cars поместим все машины той категории что пришла в функцию
            //параметром category
            IEnumerable<Car> cars = null;
            string currCategory = "";

            //если ничего не передали, то выведем все машины
            if (string.IsNullOrEmpty(category))
            {
                cars = _allCars.Cars.OrderBy(i => i.id);
            }
            else
            {
                //проверим что конкретно находится в category
                if (string.Equals("electro", category, StringComparison.OrdinalIgnoreCase))
                {
                    //выберем автомобили с категорией electro
                    cars = _allCars.Cars.Where(i => i.Category.categoryName.Equals("Электромобили")).OrderBy(i => i.id);
                    currCategory = "Электромобили";
                }

                if (string.Equals("fuel", category, StringComparison.OrdinalIgnoreCase))
                {
                    cars = _allCars.Cars.Where(i => i.Category.categoryName.Equals("Классические автомобили")).OrderBy(i => i.id);
                    currCategory = "Классические автомобили";
                }
            }

            //мы обращаемся к конкретному интерфейсу и через _allCars обращаемся к
            //функции Cars
            //var cars = _allCars.Cars;
            //передаём объект с таварами - машинами
            //затем в View мы обрпбатываем и выводим HTML страницу
            //return View(cars);

            //ещё один способ передать данные в шаблон через ViewBag
            //ViewBag.Category = "My text"
            //var cars = _allCars.Cars;
            //return View(cars);
            //во внутрь шаблона передадуться машины и ViewBag

            var carObj = new CarsListViewModel
            {
                allCars = cars,
                currCategory = currCategory
            };

            //лучший способ экспорта данных в View
             ViewBag.Title = "Страница с автомобилями";
            return View(carObj);
        }
    }
}

Shop/Controllers/HomeController.cs
using Shop.Data.Interfaces;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Shop.Controllers
{
    public class HomeController : Controller
    {
        private IAllCars _carRep;

        public HomeController(IAllCars carRep)
        {
            _carRep = carRep;
        }

        //возвращаем шаблон
        public ViewResult Index()
        {
            var honeCars = new HomeViewModel
            {
                favCars = _carRep.getFavCars
            };
            return View(honeCars);
        }
    }
}

Shop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;

        //конструктор
        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            this.allOrders = allOrders;
            this.shopCart = shopCart;
        }

        //функция возвращающая htnl шаблон
        //над этим шаблоном будут проходить действия, заполнение формы
        //событие Опляты заказа. Поэтому исп. интерфейс чтобы принимать данные
        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]//отправка методом POST
        public IActionResult Checkout(Order order)
        {
            //берем все товары из карзины и помещаем в список для удобной работы 
            shopCart.listShopItems = shopCart.getShopItems();

            //если при отправке товаров нет, то выдаём ошибку
            if (shopCart.listShopItems.Count == 0)
            {
                //выдать модельную ошибку [ключ, значение]
                ModelState.AddModelError("", "Вы не добавили товары!");
            }

            //IsValid вернёт true, если все поля введены верно
            if (ModelState.IsValid)
            {
                //оформляем заказ
                allOrders.createOrder(order);
                return RedirectToAction("Complete");
            }

            //неверная форма. Все данные вставятся в фрму и сохранятся даже
            //после перезагрузки
            return View(order);
        }

        public IActionResult Complete()
        {
            ViewBag.Message = "Заказ принят";

            return View();
        }
    }
}

Shop/Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class ShopCartController : Controller
    {
        private IAllCars _carRep;
        private readonly ShopCart _shopCart;

        public ShopCartController(IAllCars carRep, ShopCart shopCart)
        {
            _carRep = carRep;
            _shopCart = shopCart;
        }

        //позволить вызвать необходимы йшаблон и отобразить карзину
        public ViewResult Index()
        {
            var items = _shopCart.getShopItems();
            _shopCart.listShopItems = items;

            var obj = new ShopCartViewModel { shopCart = _shopCart };

            return View(obj);
        }

        //функция переадресовывает на другую страницу
        public RedirectToActionResult addToCart(int id)
        {
            //будем выбирать нужный товар из БД по id
            var item = _carRep.Cars.FirstOrDefault(i => i.id == id);

            if (item != null)
            {
                _shopCart.AddToCart(item);
            }

            //после добавления переадресуем пользователя в карзину
            return RedirectToAction("Index");
        }
    }
}

Shop/Views/Cars/List.cshtml
<h1>Все автомобили</h1>
<h3>@Model.currCategory</h3> 
<div class="row mt-5 mb-2">
    @{
        foreach (Car car in Model.allCars)
        {
            @Html.Partial("AllCars", car)
        }
    }
</div>

Shop/Views/Home/Index.cshtml
@model HomeViewModel

<h1>Лучшие автомобили</h1>
<div class="row mt-5 mb-2">
    @{
        foreach (Car car in Model.favCars)
        {
            @Html.Partial("AllCars", car)
        }
    }
</div>

Shop/Views/Order/Checkout.cshtml
@model Order

<h3>Оформление заказа</h3>
<div class="row mb-5">
        @*при нажатии на отправить форму, сработает Checkout*@
        @*method="post" при отправке формы отправляется пост-запрос [HttpPost]*@
    <form asp-action="Checkout" method="post" calss="from-horizontal">
        <div class="form-group">
            <label asp-for="name"></label>
            <div class="col-md-12">
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="surName"></label>
            <div class="col-md-12">
                <input asp-for="surName" class="form-control" />
                <span asp-validation-for="surName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="adress"></label>
            <div class="col-md-12">
                <input asp-for="adress" class="form-control" />
                <span asp-validation-for="adress" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="phone"></label>
            <div class="col-md-12">
                <input asp-for="phone" class="form-control" />
                <span asp-validation-for="phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="email"></label>
            <div class="col-md-12">
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
        </div>
        <input class="btn btn-success" type="submit" value="Оформить заказ" />
    </form>
</div>

Shop/Views/Order/Complete.cshtml
<h3>
    @ViewBag.Message
</h3>

Shop/Views/Shared/AllCars.cshtml
@model Car

<div class="col-lg-4">
    <img class="img-thumbnail" src="@Model.img" alt="@Model.name" />
    <h2>@Model.name</h2>
    <p>@Model.shortDesc</p>
    <p>Стоимость: @Model.price.ToString("c")</p>
    <p>
        <a 
           class="btn btn-warning" 
           asp-controller="ShopCart" 
           asp-action="addToCart"
           asp-route-id="@Model.id"
        >
           Добавить в карзину
        </a>
    </p>
</div>

Shop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#">Solon car</a>
                <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse" id="navbarCollapse" style="">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/List">Машины</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/List/electro">Электромобили</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Cars/List/fuel">Классические автомобили</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/ShopCart/">Корзина</a>
                        </li>
                    </ul>
                    <form class="form-inline mt-2 mt-md-0">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container mt-5">
        @RenderBody()
    </div>
    <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>© 2019-2020 Company, Inc. · <a href="#">Сограшение</a> · <a href="#">Terms</a></p>
    </footer>
    <script src="~/js/bootstrap.min.js"></script>
</body>
</html>

Shop/Views/ShopCart/Index.cshtml
@model ShopCartViewModel
<div class="container">
    @foreach (var el in Model.shopCart.listShopItems)
    { 
        <div class="alert alert-warning mt-3">
            <b>Автомобиль:</b> @el.car.name<br/>
            <b>Цена:</b> @el.car.price.ToString("c");
        </div>
    }
    <hr/>
    <a 
        class="btn btn-danger" 
        asp-controller="Order"
        asp-action="Checkout"
    >
        Оплатить
    </a>
</div>